export interface SearchBarProps {
    SMC: string;
    country: string;
}

export interface ProductDto{
    style: string,                  // Type de produit (sac, manteau, etc)
    material: string,               // Matière du produit
    color: string,                  // Couleur du produit
    sizes: Array<string>,           // Tailles du produit
    name: string,                   // Nom du produit
    description?: string,           // Description du produit
    images?: Array<string>,         // Images du produit
    sellable_retail?: boolean,       // Est-ce que le produit peut être vendu en magasin
    sellable_ecom?: boolean,         // Est-ce que le produit peut être vendu en ligne
    sellable_in?: Array<string>,    // Pays dans lesquels le produit peut être vendu
}


export const CountryList = [
    {value: 'US', label: 'United States'},
    {value: 'CA', label: 'Canada'},
    {value: 'MX', label: 'Mexico'},
    {value: 'GB', label: 'United Kingdom'},
    {value: 'DE', label: 'Germany'},
    {value: 'FR', label: 'France'},
    {value: 'IT', label: 'Italy'},
    {value: 'ES', label: 'Spain'},
    {value: 'NL', label: 'Netherlands'},
    {value: 'SE', label: 'Sweden'},
    {value: 'NO', label: 'Norway'},
    {value: 'DK', label: 'Denmark'},
    {value: 'FI', label: 'Finland'},
    {value: 'IE', label: 'Ireland'},
    {value: 'CH', label: 'Switzerland'},
    {value: 'AT', label: 'Austria'},
    {value: 'BE', label: 'Belgium'},
    {value: 'LU', label: 'Luxembourg'},
    {value: 'PT', label: 'Portugal'},
    {value: 'GR', label: 'Greece'},
    {value: 'RU', label: 'Russia'},
    {value: 'JP', label: 'Japan'},
    {value: 'CN', label: 'China'},
    {value: 'HK', label: 'Hong Kong'},
    {value: 'KR', label: 'South Korea'},
    {value: 'TW', label: 'Taiwan'},
    {value: 'SG', label: 'Singapore'},
    {value: 'AU', label: 'Australia'},
    {value: 'NZ', label: 'New Zealand'},
    {value: 'AR', label: 'Argentina'},
    {value: 'BR', label: 'Brazil'},
    {value: 'CL', label: 'Chile'},
    {value: 'CO', label: 'Colombia'},
    {value: 'CR', label: 'Costa Rica'},
    {value: 'DO', label: 'Dominican Republic'},
    {value: 'EC', label: 'Ecuador'},
    {value: 'SV', label: 'El Salvador'},
    {value: 'GT', label: 'Guatemala'},
    {value: 'HN', label: 'Honduras'},
    {value: 'NI', label: 'Nicaragua'},
    {value: 'PA', label: 'Panama'},
    {value: 'PY', label: 'Paraguay'},
    {value: 'PE', label: 'Peru'},
    {value: 'PR', label: 'Puerto Rico'},
    {value: 'UY', label: 'Uruguay'},
    {value: 'VE', label: 'Venezuela'},
    {value: 'DZ', label: 'Algeria'},
    {value: 'AO', label: 'Angola'},
    {value: 'BJ', label: 'Benin'},
    {value: 'BW', label: 'Botswana'},
    {value: 'BF', label: 'Burkina Faso'},
    {value: 'BI', label: 'Burundi'},
    {value: 'CM', label: 'Cameroon'},
    {value: 'CV', label: 'Cape Verde'},
    {value: 'CF', label: 'Central African Republic'},
    {value: 'TD', label: 'Chad'},
    {value: 'KM', label: 'Comoros'},
    {value: 'CG', label: 'Congo - Brazzaville'},
    {value: 'CD', label: 'Congo - Kinshasa'},
    {value: 'CI', label: 'Côte d’Ivoire'},
    {value: 'DJ', label: 'Djibouti'},
    {value: 'EG', label: 'Egypt'},
    {value: 'GQ', label: 'Equatorial Guinea'},
    {value: 'ER', label: 'Eritrea'},
    {value: 'ET', label: 'Ethiopia'},
    {value: 'GA', label: 'Gabon'},
    {value: 'GM', label: 'Gambia'},
    {value: 'GH', label: 'Ghana'},
    {value: 'GN', label: 'Guinea'},
    {value: 'GW', label: 'Guinea-Bissau'},
    {value: 'KE', label: 'Kenya'},
    {value: 'LS', label: 'Lesotho'},
    {value: 'LR', label: 'Liberia'},
    {value: 'LY', label: 'Libya'},
    {value: 'MG', label: 'Madagascar'},
    {value: 'MW', label: 'Malawi'},
    {value: 'ML', label: 'Mali'},
    {value: 'MR', label: 'Mauritania'},
    {value: 'MU', label: 'Mauritius'},
    {value: 'YT', label: 'Mayotte'},
    {value: 'MA', label: 'Morocco'},
    {value: 'MZ', label: 'Mozambique'},
    {value: 'NA', label: 'Namibia'},
    {value: 'NE', label: 'Niger'},
    {value: 'NG', label: 'Nigeria'},
    {value: 'RW', label: 'Rwanda'},
    {value: 'RE', label: 'Réunion'},
    {value: 'SH', label: 'Saint Helena'},
    {value: 'SN', label: 'Senegal'},
    {value: 'SC', label: 'Seychelles'},
    {value: 'SL', label: 'Sierra Leone'},
    {value: 'SO', label: 'Somalia'},
    {value: 'ZA', label: 'South Africa'},
    {value: 'SD', label: 'Sudan'},
    {value: 'SZ', label: 'Swaziland'},
    {value: 'ST', label: 'São Tomé and Príncipe'},
    {value: 'TZ', label: 'Tanzania'},
    {value: 'TG', label: 'Togo'},
    {value: 'TN', label: 'Tunisia'},
    {value: 'UG', label: 'Uganda'},
    {value: 'EH', label: 'Western Sahara'},
    {value: 'ZM', label: 'Zambia'},
    {value: 'ZW', label: 'Zimbabwe'},
    {value: 'AF', label: 'Afghanistan'},
    {value: 'AM', label: 'Armenia'},
];



